[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/css/*"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/static/js/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"