services:
  # Backend Service
  - type: web
    name: apex-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    # Add these in Render dashboard:
    # - JWT_SECRET
    # - GEMINI_API_KEY
    # - FRONTEND_URL

  # Frontend Service
  - type: web
    name: apex-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /static/css/*
        name: Content-Type
        value: text/css
      - path: /static/js/*
        name: Content-Type
        value: application/javascript
    envVars:
      - key: REACT_APP_API_URL
        value: https://apex-backend.onrender.com